! Task:
! 
! For a maze generated by this task, write a function that finds (and
! displays) the shortest path between two cells.
! 
! Note that because these mazes are generated by the Depth-first search
! algorithm, they contain no circular paths, and a simple depth-first tree
! search can be used.

