! Introduction
! 
! The Cocke–Younger–Kasami algorithm (CYK algorithm, also known as CKY
! algorithm) is a parsing algorithm for context-free grammars. It
! determines whether a given string can be generated by the grammar
! (membership problem) and, if so, can be extended to produce a parse
! tree. The algorithm uses dynamic programming and requires the grammar to
! be in Chomsky normal form (CNF).
! 
! Problem
! 
! Given a context-free grammar G in Chomsky normal form and a string w of
! length n, decide whether w is in the language generated by G.
! 
! Chomsky Normal Form
! 
! A context-free grammar is in CNF if every production rule is of the
! form:
! 
! A → BC
! or
! 
! A → a
! where A, B, C are non-terminal symbols, and a is a terminal symbol. (The
! start symbol may also have a production to the empty string ϵ, but for
! membership testing of non-empty strings, this is often handled
! separately.)
! 
! Any context-free grammar can be converted to an equivalent one in CNF.
! 
! Algorithm Description
! 
! The CYK algorithm fills a triangular table T where T[i, j] (with j ≥ i)
! is the set of non-terminals that can derive the substring
! w_(i + 1)…w_(j + 1) (using 1-based indexing for the string).
! 
! The table is filled bottom-up:
! 
! -   For substrings of length 1 (l = 1): For each position i from 1 to n,
!     add non-terminal A to T[i, i] if there is a production A → w_(i).
! 
! -   For substring lengths l = 2  to  n:
! 
!  For each starting position i from 1 to n - l + 1, let j = i + l - 1.  
!  For each possible split point k from i to j-1:  
!    For each production A → BC:  
!      If B ∈ T[i,k] and C ∈ T[k+1,j], add A to T[i,j].
! 
! The string w is accepted if the start symbol S is in T[1, n].
! 
! Pseudocode
! 
!     Let w be the string of length n, indexed from 1 to n.
!     Let T be an (n × n) table, initialized empty (sets of non-terminals).
! 
!     // Base case: length 1
!     for i = 1 to n:
!         for each production A → w_i:
!             add A to T[i,i]
! 
!     // Longer lengths
!     for l = 2 to n:                  // substring length
!         for i = 1 to n - l + 1:       // start position
!             j = i + l - 1             // end position
!             for k = i to j-1:         // split point
!                 for each production A → B C:
!                     if B in T[i,k] and C in T[k+1,j]:
!                         add A to T[i,j]
! 
!     if S in T[1,n]:
!         accept
!     else:
!         reject
! 
! Complexity
! 
! -   Time: O(n³|G|), where |G| is the size of the grammar (number of
!     productions). Since |G| is constant for a fixed grammar, typically
!     stated as O(n³).
! -   Space: O(n²).
! 
! Extensions
! 
! The basic algorithm is a recognizer. It can be extended to produce parse
! trees by storing backpointers in the table entries. It can also handle
! weighted or probabilistic context-free grammars by storing weights or
! probabilities instead of sets.
! 
! Example
! 
! You need to implement the CYK algorithm applied to a simple context-free
! grammar for noun phrases, loosely in Chomsky normal form (with unit
! productions allowed for terminals and some adjectives).
! 
! Grammar Rules
! 
! -   NP → Det Nom
! -   Nom → AP Nom | book | orange | man
! -   AP → Adv A | heavy | orange | tall
! -   Det → a
! -   Adv → very | extremely
! -   A → heavy | orange | tall | muscular
! 
! (Note: This grammar allows recursive adjective phrases, e.g., "very
! heavy orange".)


